<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- <OutputType>Exe</OutputType> -->
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="*" />
    <PackageReference Include="Amazon.Lambda.Annotations" Version="*" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="AWSSDK.Bedrock" Version="*" />
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="*" />
    <PackageReference Include="AWSSDK.BedrockAgentRuntime" Version="*" />
    <PackageReference Include="AWSSDK.S3" Version="*" />
    <PackageReference Include="JsonSchema.Net" Version="*"/>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0"/>
    <!-- <PackageReference Include="Aspose.Slides.NET" Version="*" /> -->
  </ItemGroup>
  <ItemGroup>
    <None Update="config/pptx_example_single_shot.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="template/pptx_base_template.pptx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="template/presentation_template_mapping.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="template/default_bkg.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="presentation_slides.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>